# Generated by Django 4.2.14 on 2024-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
