# Generated by Django 4.2.14 on 2024-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_timestamp_message_created_at_alter_chat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField()),
                ('chatbot_response', models.TextField()),
                ('timestamp_prompt', models.DateTimeField(auto_now_add=True)),
                ('timestamp_response', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
